import { PERMISSIONS } from './permissions.js'

export const MANAGER_ALLOWED_PERMISSIONS = [
  // Dashboard
  PERMISSIONS.VIEW_DASHBOARD,

  // Tenants
  PERMISSIONS.VIEW_TENANTS,
  PERMISSIONS.ADD_TENANTS,
  PERMISSIONS.EDIT_TENANTS,
  PERMISSIONS.UPDATE_TENANTS,
  PERMISSIONS.REMOVE_TENANTS,

  // Rooms
  PERMISSIONS.VIEW_ROOMS,
  PERMISSIONS.ADD_ROOMS,
  PERMISSIONS.EDIT_ROOMS,
  PERMISSIONS.REMOVE_ROOMS,

  PERMISSIONS.VIEW_ALLOCATIONS,
  PERMISSIONS.ADD_ALLOCATIONS,
  PERMISSIONS.EDIT_ALLOCATIONS,
  PERMISSIONS.REMOVE_ALLOCATIONS,

  // Payments
  PERMISSIONS.VIEW_PAYMENTS,
  PERMISSIONS.COLLECT_RENT,
  PERMISSIONS.ADD_DUES,
  PERMISSIONS.VIEW_PAYMENT_SETTINGS,
  PERMISSIONS.MANAGE_PAYMENT_SETTINGS,

  PERMISSIONS.VERIFY_PAYMENTS,
  PERMISSIONS.REJECT_PAYMENTS,

  // Expenses
  PERMISSIONS.VIEW_EXPENSES,
  PERMISSIONS.ADD_EXPENSES,
  PERMISSIONS.EDIT_EXPENSES,
  PERMISSIONS.REMOVE_EXPENSES,

  // Complaints
  PERMISSIONS.VIEW_COMPLAINTS,
  PERMISSIONS.MANAGE_COMPLAINTS,

  // Bookings
  PERMISSIONS.VIEW_BOOKINGS,
  PERMISSIONS.MANAGE_BOOKINGS,

  // Documents
  PERMISSIONS.VIEW_DOCUMENTS,
  PERMISSIONS.MANAGE_DOCUMENTS,

  // Staff
  PERMISSIONS.VIEW_STAFF,
  PERMISSIONS.MANAGE_STAFF,

  // Food
  PERMISSIONS.MANAGE_FOOD_MENU,

  // Announcements
  PERMISSIONS.SEND_ANNOUNCEMENT,
]
