import { PERMISSIONS } from './permissions.js'

export const STAFF_ALLOWED_PERMISSIONS = [
  // Dashboard
  PERMISSIONS.VIEW_DASHBOARD,

  // Tenants
  PERMISSIONS.VIEW_TENANTS,
  PERMISSIONS.ADD_TENANTS,
  PERMISSIONS.EDIT_TENANTS,
  PERMISSIONS.UPDATE_TENANTS,

  // Rooms & Beds
  PERMISSIONS.VIEW_ROOMS,

  // Allocations
  PERMISSIONS.VIEW_ALLOCATIONS,
  PERMISSIONS.ADD_ALLOCATIONS,
  PERMISSIONS.EDIT_ALLOCATIONS,

  // Rent & Dues
  PERMISSIONS.VIEW_DUES,
  PERMISSIONS.ADD_DUES,

  // Payments
  PERMISSIONS.VIEW_PAYMENTS,
  PERMISSIONS.COLLECT_RENT,

  // Expenses
  PERMISSIONS.VIEW_EXPENSES,
  PERMISSIONS.ADD_EXPENSES,
  PERMISSIONS.EDIT_EXPENSES,
  PERMISSIONS.REMOVE_EXPENSES,

  // Complaints
  PERMISSIONS.VIEW_COMPLAINTS,
  PERMISSIONS.MANAGE_COMPLAINTS,

  // Bookings
  PERMISSIONS.VIEW_BOOKINGS,
  PERMISSIONS.MANAGE_BOOKINGS,

  // Documents
  PERMISSIONS.VIEW_DOCUMENTS,

  // Announcements
  PERMISSIONS.SEND_ANNOUNCEMENT,
]